baseURL = 'https://derossimolina.com.br/'
languageCode = 'en-us'
title = 'J. de Rossi Molina'
theme = 'hugo-digital-garden-theme'
copyright = '© 2024 J. de Rossi Molina'    


[params]
  name = "J. de Rossi Molina"
  description = "PhD in History that writes international politics and data science"


  [[params.social]]
    name = "Github"
    link = "https://github.com/jeronimo-molina"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/molinajeronimo/"
    icon = "fab fa-linkedin-in"

[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Library"
    url = "/library/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'