baseURL = 'https://derossimolina.com.br/'
languageCode = 'en-us'
title = 'J. de Rossi Molina'
theme = 'hextra'
copyright = '© 2024-2025 J. de Rossi Molina'    
defaultContentLanguage = "en"

[pagination]
pagerSize = 5

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
section = [ "HTML", "RSS" ]


[params.author]
name = "J. de Rossi Molina"
email  = "jeronimo@derossimolina.com.br"
location = "Sao Paulo, Brazil"

[params]
description = "PhD candidate in History that writes about international politics and data science."
dateFormat = "2006-01-02"
paginationSinglePost = true

# icp = "京ICP备xxxxx号-1" # for China ICP license
# police = "京公网安备 12345678号" # for China police beian

colorTheme = "auto"
colorThemeSwitcher = true

readMore = true
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
math = true # true: enable mathjax globally (default is false)
toc = true

[params.footer]
enable = true
displayCopyright = true
displayPoweredBy = false
width = "normal"

[params.theme]
default = "light"
displayToggle = true

[params.search]
enable = true
type = "flexsearch"

[params.search.flexsearch]
    index = "title"
    tokenize = "forward"

[params.highlight.copy]
enable = true
display = "hover"


social = [
    { id = "github", url = "https://github.com/jeronimo-molina" },
    { id = "linkedin", url = "https://www.linkedin.com/in/molinajeronimo" },
    { id = "email", url = "jeronimo@derossimolina.com.br" },
    { id = "x", url = "https://x.com/jdermolina" },
]

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 3

[[languages.en.menu.main]]
name = "Papers"
identifier = "papers"
url = "/papers/"
weight = 4

[[languages.en.menu.main]]
name = "Docs"
identifier = "docs"
url = "/docs/"
weight = 5

[languages]
[languages.en]
languageName = "English"

[languages.pt]
languageName = "Português"

[[languages.pt.menu.main]]
identifier = "home"
name = "Início"
url = "/"
weight = 1

[[languages.pt.menu.main]]
identifier = "about"
name = "Sobre"
url = "/about/"
weight = 2

[[languages.pt.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 3

[[languages.pt.menu.main]]
identifier = "papers"
name = "Artigos Científicos"
url = "/papers/"
weight = 4

[[languages.pt.menu.main]]
identifier = "docs"
name = "Documentos"
url = "/docs/"
weight = 5


[languages.pt.params]
languageCode = "pt-br"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/
tabWidth           = 4
